gg:
  jte:
    development-mode: true
spring:
  application:
    name: spring-jte
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id:
            client-secret:
            scope: openid, profile, email
          entra-id:
            client-id:
            client-secret:
            scope: openid, profile, email
          github:
            client-id:
            client-secret:
            scope:
              - user:email
              - read:user
          google:
            client-id:
            client-secret:
            scope:
              - openid
              - profile
              - email
        provider:
          okta:
              issuer-uri: https://dev-09980417.okta.com
          entra-id:
              issuer-uri: https://login.microsoftonline.com/1b286c40-c2fd-46d5-a553-b6502b89f42d/v2.0

logging.level:
  org.springframework.security: DEBUG
